#!/bin/bash

set -e
set -o pipefail
set -x

targets=($(find bsp -name settings.mk | cut -d '/' -f 2)) 

programs=($(ls software))

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

CONFIGURATION=debug

# Run regression tests
for target in ${targets[@]}
do
    for program in "${programs[@]}"
    do
        # Coremark and Dhrystone don't fit
        if [ "${program}" == "dhrystone" -o "${program}" == "coremark" -o "${program}" == "example-freertos-blinky-systemview" ] ; then
            continue
        fi

	# mc examples are broken
	if [ "${program}" == "example-freertos-mc" -o "${program}" == "example-freertos-blinky-mc" ]; then
	    continue
	fi

	# can't push to example-i2c or example-pwm yet, so they're broken
	if [ "${program}" == "example-i2c" -o "${program}" == "example-pwm" ]; then
	    continue
	fi

        make TARGET="${target}" PROGRAM="${program}" CONFIGURATION="${CONFIGURATION}" -j${nproc} software
        make TARGET="${target}" PROGRAM="${program}" CONFIGURATION="${CONFIGURATION}" clean-software
    done
    make TARGET="${target}" clean
done

echo "PASSED"

